repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.1.0
  hooks:
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.31.0
  hooks:
    - id: terraform_fmt

- repo: https://bitbucket.cityntl.com/scm/tfe/terraform-pre-commit.git
  rev: v1.33.0
  hooks:
    - id: terraform_docs_replace
    - id: terraform_module_path_replace.py